name: 'Deploy Sponge Plugins to Ore'
description: 'Deploy a given Sponge plugin to Ore using the v2 API'
branding: 
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  plugin:
    description: 'Plugin to upload based on the key from the '
    required: true
  description:
    description: 'Version Description - can be a file name or a string'
    required: true
  apiKey:
    description: 'The Ore API key to use'
    required: true
  channel:
    description: 'The channel to assign the release to. Note that this may be deprecated in future.'
    required: false
  pluginId:
    description: 'The plugin ID'
    required: true
  oreUrl:
    description: 'The Ore base URL'
    required: true
    default: 'https://ore.spongepowered.org/'
  createForumPost:
    description: 'Whether to create a forum post'
    required: true
    default: 'true'
  verboseLogging:
    description: 'Whether to display verbose logging'
    required: true
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
